# Generated by Django 3.2 on 2021-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date_finish',
            field=models.DateField(verbose_name='Дата конца опроса'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала опроса'),
        ),
    ]
